### ISSUE TITLE
felint lint not working

### ISSUE THREAD

**Issue by falstack** [youzan/felint#9]
![image](https://user-images.githubusercontent.com/16357724/39690636-60ea014c-520d-11e8-9349-6311ab2d34e7.png)

**Comment by falstack** [comment]
felint version：1.0.5
OS：macOS Sierra 10.12.6 (16G29)

**Comment by flasco** [comment]
It not have any instructions about `felint lint`.

**Comment by falstack** [comment]
@flasco 
兄弟，过了几个月了，你才回复我。。。

很明显我 install 了 felint，然后按照文档上的 step1 执行 `felint init`，然后没有生成任何文件，也没有报错，你居然给我说没有任何与之相关的说明。。。

加油吧

**Comment by flasco** [comment]
你仔细看看你的截图，你写的是 lint 初始化是 init。我想说的是没有一条指令是 felint lint ，不是没有说明

**Comment by flasco** [comment]
还有我也是今天刚点进来 我又不是contributor

**Comment by falstack** [comment]
@flasco 原来你不是 contributor 啊！！抱歉抱歉，不知道 contributor 去哪里了哎
我第三行就是`felint lint`

**Comment by flasco** [comment]
对 所以是你输入错误了，初始化是init，根本没有一条指令是lint的，当然就没反应了
